FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY client/package*.json ./client/
RUN cd client && npm install

RUN mkdir -p /data

EXPOSE 3000 5173

CMD ["npm", "run", "dev"]
